version: '3'
services:
  eureka-server1:
    container_name: eureka-server1
    restart: always
    ports:
      - "8761:8761"
    build: ./Eureka_Server
    networks:
      - app-network
  gateway-server:
    container_name: gateway_server
    restart: always
    ports:
      - "8889:8889"
    build: ./Gateway
    environment:
      - EUREKA_SERVER=eureka-server1
    networks:
      - app-network

  service_client:
    container_name: service_client
    restart: always
    ports:
      - "8089:8089"
    build:
      context: ./Client
      dockerfile: Dockerfile
    environment:
      - EUREKA_SERVER=eureka-server1
      - MYSQL_HOST=mysql2
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_PORT=3306
    depends_on:
      - eureka-server1
      - mysql2
    networks:
      - app-network

  service_voiture:
    container_name: SERVICE_VOITURE
    restart: always
    ports:
      - "8085:8085"
    build:
      context: ./Voiture
      dockerfile: Dockerfile
    environment:
      - EUREKA_SERVER=eureka-server1
      - MYSQL_HOST=mysql2
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_PORT=3306
    depends_on:
      - eureka-server1
      - mysql2
    networks:
      - app-network

  mysql2:
    container_name: mysql2
    image: mysql:latest
    ports: 
      - "3306:3306"
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app-network

volumes:
  mysql:

networks:
  app-network:
    driver: bridge
